title: kaguya's blog
email: my@kaguya.org
description: >-
  read & write for myself.
  interest in computer, math and other complex superstructures.
  
baseurl: /
url: https://kaguya.org
twitter_username: kaguyamoe
github_username:  0kaguya

markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed

permalink: none

karmdown:
  parse_block_html: true
