title: kaguya's blog
email: my@kaguya.org
description: >-
  read & write for self construction.
  interest in computer, math and other things about complexity.
  
baseurl: /
url: https://kaguya.org
twitter_username: kaguyamoe
github_username:  0kaguya

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: none
